### ISSUE TITLE
Not injecting on emulator (ptrace injector works but not preload)

### ISSUE THREAD

**Issue by 77friends** [reveny/Android-LD-Preload-Injector#2]
Im trying to use this on an emulator (ldplayer 4, 32 bit) and it wont inject.

I am using an x86 lib, to match the x86 architecture in my emulator, and it does not work.

Your ptrace injector does work, with the same lib I am using, but it does not work with ld_preload. (I even tried the lib and apk you sent in issue #1 )

After I inject and try to open the app, my emulator just freezes at the home screen, and I cant open anything (I had this same issue with my own ld_preload injector i had made a while ago)

**Comment by MikaCybertron** [comment]
> Im trying to use this on an emulator (ldplayer 4, 32 bit) and it wont inject.
> 
> I am using an x86 lib, to match the x86 architecture in my emulator, and it does not work.
> 
> Your ptrace injector does work, with the same lib I am using, but it does not work with ld_preload. (I even tried the lib and apk you sent in issue #1 )
> 
> After I inject and try to open the app, my emulator just freezes at the home screen, and I cant open anything (I had this same issue with my own ld_preload injector i had made a while ago)

same for me, it just freezes/stuck at home screen of ldplayer, so I think LD_PRELOAD doesn't work for emulator

**Comment by 77friends** [comment]
> > Im trying to use this on an emulator (ldplayer 4, 32 bit) and it wont inject.
> > I am using an x86 lib, to match the x86 architecture in my emulator, and it does not work.
> > Your ptrace injector does work, with the same lib I am using, but it does not work with ld_preload. (I even tried the lib and apk you sent in issue #1 )
> > After I inject and try to open the app, my emulator just freezes at the home screen, and I cant open anything (I had this same issue with my own ld_preload injector i had made a while ago)
> 
> same for me, it just freezes/stuck at home screen of ldplayer, so I think LD_PRELOAD doesn't work for emulator

Yeah, a long time ago I tried LD_PRELOAD on my own and had the same issue.

Although, it does say that it works for "all device architectures" in the readme

Maybe reveny knows something we dont?

**Comment by reveny** [comment]
> Although, it does say that it works for "all device architectures" in the readme

Well, I have only tested it on the Android Studio emulator and it works there. I am not exactly sure what the difference between these Game Emulators and normal Android Emulators is but there is something on game emulators that prevents certain things. My theory is that the game emulator has a modified version of android x86 with a custom launcher that may cause the problems. For now I can only tell you to use the ptrace Injector for these emulators.
